### ISSUE TITLE
新浪图床的外链被屏蔽了

### ISSUE THREAD

**Issue by horizon98** [wah0713/myTampermonkey#10]
首先感谢大佬写得脚本，斗鱼网页版的观感好了不少。
但是现在设置里面的一些图标和图片因为新浪图床防外链无法显示，大佬可以考虑换个图床或者用其它方法绕过限制。
涉及图片：
https://s3.ax1x.com/2020/12/03/D7YZpd.jpg
https://wx2.sinaimg.cn/mw690/8666830cgy1g9xp15vwl4j20i20jdwey.jpg
https://s3.ax1x.com/2020/12/03/D7JIln.jpg

辛苦啦

**Comment by wah0713** [comment]
人变懒了

**Comment by wah0713** [comment]
人变懒了
