### ISSUE TITLE
关于“登录最高画质”的问题

### ISSUE THREAD

**Issue by ra1nbow2000** [wah0713/myTampermonkey#2]
脚本整体已经非常完善了，但是开启了“登录最高画质”这个选项后，在进入提供8/10M的直播间时还是以4M的码率播放，然后会在几秒种后自动刷新一下变为更高的画质，这是在h5播放器的情况下，当在flash播放器（虽然没人用）的情况下，基本就不起作用了。
斗鱼也是账号已登录状态，其实这个功能主要作用对于我就是省去了每次进入直播间切换清晰度点的那几下鼠标，虽然每次都会自动刷新一下也无伤大雅，但是能改进为进入房间就是最高画质我相信用起来也更舒服，也更契合强迫症患者。
这是一点小小的反馈和建议

**Comment by wah0713** [comment]
兄弟就是因为没有办法避免刷新一下，所以我才弄了一个选项按钮。 






在 2019-05-02 19:39:15，"剑开云海" <notifications@github.com> 写道：


脚本整体已经非常完善了，但是开启了“登录最高画质”这个选项后，在进入提供8/10M的直播间时还是以4M的码率播放，然后会在几秒种后自动刷新一下变为更高的画质，这是在h5播放器的情况下，当在flash播放器（虽然没人用）的情况下，基本就不起作用了。
斗鱼也是账号已登录状态，其实这个功能主要作用对于我就是省去了每次进入直播间切换清晰度点的那几下鼠标，虽然每次都会自动刷新一下也无伤大雅，但是能改进为进入房间就是最高画质我相信用起来也更舒服，也更契合强迫症患者。
这是一点小小的反馈和建议
