### ISSUE TITLE
弹幕一多直播就会卡住

### ISSUE THREAD

**Issue by Jesse1uo** [wah0713/myTampermonkey#23]
弹幕一多就会直接卡住
就是直播画面和声音都会卡住
但是弹幕本身不会卡
开斗鱼自带的精简弹幕模式就会好很多
不清楚具体是哪个功能造成的

**Comment by wah0713** [comment]
2.00版本已经做更新了

**Comment by wah0713** [comment]
昨晚找了一个人多的直播，效果不容乐观。这几天还会继续关注这个问题

**Comment by wah0713** [comment]
这个问题最新版本，已经修复，请手动更新
