### ISSUE TITLE
关于礼物区的问题

### ISSUE THREAD

**Issue by ra1nbow2000** [wah0713/myTampermonkey#3]
![image](https://user-images.githubusercontent.com/32125748/59041989-38310580-88ac-11e9-8608-e130aa83069d.png)
在某些情况下,登录到最高画质后播放框下面的礼物栏会消失,留下一行白条.这是出现的问题
能不能直接添加一个移除礼物栏的功能,然后更改"网页全屏模式"的元素大小,就是放大播放器的尺寸,让右侧的聊天框变窄一点然后填充下面礼物栏的留白,这样看起来整个网页也会更饱满观感也更舒服

**Comment by wah0713** [comment]
抱歉兄弟，那个礼物不显示是我引入外链的问题，暂时没有时间管了。因为个人原因，这个脚本将来也不会有大改动。
