### ISSUE TITLE
[enhancement] PK进度条屏蔽

### ISSUE THREAD

**Issue by backuponeday** [wah0713/myTampermonkey#34]
**version**: 2.4.1

请增加一个屏蔽 Pk 进度条的功能.
现在斗鱼有两种 PK 进度条 `".MorePk"` 多人 Pk , `".PkView"` 单人 Pk .于是我添加的以下代码,
由于我不会写代码, 导致 Pk 进度条还没有出现,而我添加的这段代码就跑过了, 所以每次都需要点关闭再打开再关闭才能工作,
希望你能完善一下.谢谢
```js
  removePk: {
      name: '移除pk',
      description: '移除pk遮挡',
      value: true,
      action: async (value) => {
          if (value){
              $(".MorePk").remove();
              $(".PkView").remove();
          }
        }
      }

**Comment by wah0713** [comment]
> **version**: 2.4.1
> 
> 请增加一个屏蔽 Pk 进度条的功能. 现在斗鱼有两种 PK 进度条 `".MorePk"` 多人 Pk , `".PkView"` 单人 Pk .于是我添加的以下代码, 由于我不会写代码, 导致 Pk 进度条还没有出现,而我添加的这段代码就跑过了, 所以每次都需要点关闭再打开再关闭才能工作, 希望你能完善一下.谢谢
> 
> ```js
>   removePk: {
>       name: '移除pk',
>       description: '移除pk遮挡',
>       value: true,
>       action: async (value) => {
>           if (value){
>               $(".MorePk").remove();
>               $(".PkView").remove();
>           }
>         }
>       }
> ```

首先谢谢你提的意见。
已经了解你的需求了，请手动更新到2.4.2版本。
你都写到这个程度，很难相信不懂代码。🥺
