### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by 0xLac** [wah0713/myTampermonkey#35]
作者你好，因为我看直播喜欢长时间挂着，但是斗鱼长时间屏幕不动的话它会黑屏并提示你是否还在屏幕前，我觉得这个很烦人。
可不可以把这个提示优化掉，这个对我这种人喜欢挂机的用户还挺重要的，谢谢。

**Comment by wah0713** [comment]
这个测试太难了，每次又要等15分钟。做不了
