### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by wulawaya** [wah0713/myTampermonkey#39]
使用你开发的插件效果很好，使用很方便。在此表示感谢！

因为我观看斗鱼都是看电影直播，需要积分，进入直播间需要     #打开 或者  #签到 来获取点播积分，如果方便希望增加进入自动发送 这两个字符的功能。

**Comment by wah0713** [comment]
谢谢你的使用，我构思一会我打算这样做，首先让用户配置关键词和间隔时间还有触发的关键的词频。当页面检测到弹幕出现关键词和出现达到词频。然后用户就会发送。

**Comment by wah0713** [comment]
后来一直没有时间，这个复杂度还是挺高的。假如要做还不如新开一个脚本。没有精力了。就这样吧
