### ISSUE TITLE
建议添加一个功能，双击直播区域改成全屏，而不是默认的网页全屏

### ISSUE THREAD

**Issue by Li-Jinxuan** [wah0713/myTampermonkey#42]
进入直播间后习惯的点击直播右下角的全屏观看，但是斗鱼直播区域右下角的全屏按钮总是加载的很慢，要等一会才能点。改成双击全屏的话就不用等按钮加载好能直接双击全屏看了

**Comment by wah0713** [comment]
抱歉不做这个功能，能力有限
